// <auto-generated />
using System;
using Afslutningsprojekt.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Afslutningsprojekt.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Afslutningsprojekt.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2022, 5, 16, 10, 18, 30, 307, DateTimeKind.Local).AddTicks(3904),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unikum Munikums first t-shirt design to be introduced to the website",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/2/24/Blue_Tshirt.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 200m,
                            Price = 100m,
                            Title = "testing T-shirt flag 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DateCreated = new DateTime(2022, 5, 16, 10, 18, 30, 307, DateTimeKind.Local).AddTicks(3940),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unikum Munikums second t-shirt design to be introduced to the website",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/2/24/Blue_Tshirt.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 200m,
                            Price = 99m,
                            Title = "testing T-shirt 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateCreated = new DateTime(2022, 5, 16, 10, 18, 30, 307, DateTimeKind.Local).AddTicks(3942),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unikum Munikums ordinary shirt",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/2/24/Blue_Tshirt.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 200m,
                            Price = 99m,
                            Title = "testing T-shirt 2"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            DateCreated = new DateTime(2022, 5, 16, 10, 18, 30, 307, DateTimeKind.Local).AddTicks(3944),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unikum Munikums second t-shirt design to be introduced to the website",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/2/24/Blue_Tshirt.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 200m,
                            Price = 99m,
                            Title = "testing T-shirt"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            DateCreated = new DateTime(2022, 5, 16, 10, 18, 30, 307, DateTimeKind.Local).AddTicks(3946),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unikum Munikums second t-shirt design to be introduced to the website",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/2/24/Blue_Tshirt.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 200m,
                            Price = 99m,
                            Title = "ugly testing T-shirt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
